name: A workflow for my hello work file
on: push
jobs:
  build:
    name: Hello work action
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: ./action-a
       with:
         MY_NAME: "Mona"
